# Site metadata

site_name: Project Fusion -  Architectural  Decision Records
site_description: Approved ADR's for that provide guidance and agreed upon methods for common patterns. 
site_author: American Refining Group
site_url: http://localhost.com  # Update for your hosting URL

# Repository information (optional, for GitHub Pages or similar)
repo_name: TBD
repo_url: http://TBD.com

# Theme configuration
theme:
  name: material  # Material for MkDocs for a modern, responsive design
  palette:
    scheme: slate  # Auto-switch between light and dark mode
    primary: indigo  # Customize primary color
    accent: amber    # Customize accent color
  features:
    - content.code.copy  # Enable copy button for code blocks
    - content.tabs       # Enable tabbed content
    - navigation.sections  # Group pages into sections
    - search.suggest      # Search suggestions
    - search.highlight   # Highlight search terms
    - palette.toggle     # Enable theme switcher icon

# Plugins
plugins:
  - search              # Built-in search plugin
  - awesome-pages       # Auto-generate TOC from nested folder structure

# Markdown extensions for enhanced formatting
markdown_extensions:
  - admonition          # Support for callouts (notes, warnings, etc.)
  - pymdownx.details    # Collapsible sections
  - pymdownx.superfences  # Advanced code block formatting
  - pymdownx.highlight: # Syntax highlighting for code
      linenums: true    # Add line numbers to code blocks
  - toc:                # In-page table of contents
      permalink: true   # Add anchor links to headings
  - pymdownx.emoji:     # Emoji support
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed     # Support for tabbed content
  - attr_list           # Allow custom attributes in Markdown
  - md_in_html          # Allow HTML in Markdown



# Optional: Extra settings for advanced features
extra:
  social:  # Add links to social or repo pages
    - icon: fontawesome/brands/github
      link: https://github.com/your-username/your-repo
  generator: false  # Hide "Made with MkDocs" footer